[package]
name = "shrubbery"
version = "0.2.0"
edition = "2024"

[features]
default = ["serde", "bevy"]
serde = ["dep:serde", "glam/serde"]
bevy = ["dep:bevy"]

[dependencies]
glam = "0.33"
rand = "0.10"
rand_chacha = "0.10"
thiserror = "2.0"

bevy = {version = "0.17.3", features = ["file_watcher"], optional = true}
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true, }

[dev-dependencies]
kiss3d = "0.37"
